/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    //"aws_cognito_identity_pool_id": "us-east-2:c5f0ba09-1f39-440e-8ae1-cf847729c722",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_xqXbetEcq",
//     "aws_user_pools_web_client_id": "4covvff1i78s0s9pjb024h1alc",
//     "oauth": {},
    "aws_user_files_s3_bucket": "octankretail03a10f66e2434780b7b3a2aed757a4e6122751-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://7edscnrvazhrjhfalanfnkhayy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3b6urjffsjdd5cminuemnpoc2m"
};


export default awsmobile;
